from django.core.management.base import BaseCommand
from cars.models import Make, Car
from django.contrib.auth.models import User
from datetime import date, timedelta
import random

class Command(BaseCommand):
    help = 'Create comprehensive sample data for the car showroom'
    
    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.SUCCESS('Creating sample data...'))
        
        # Create sample makes
        makes_data = [
            {'name': 'Mercedes-Benz', 'country': 'Germany', 'founded_year': 1926, 'description': 'German luxury automotive brand'},
            {'name': 'BMW', 'country': 'Germany', 'founded_year': 1916, 'description': 'Bavarian Motor Works'},
            {'name': 'Audi', 'country': 'Germany', 'founded_year': 1909, 'description': 'German luxury car manufacturer'},
            {'name': 'Tesla', 'country': 'USA', 'founded_year': 2003, 'description': 'Electric vehicle manufacturer'},
            {'name': 'Porsche', 'country': 'Germany', 'founded_year': 1931, 'description': 'German sports car manufacturer'},
            {'name': 'Lexus', 'country': 'Japan', 'founded_year': 1989, 'description': 'Luxury division of Toyota'},
            {'name': 'Jaguar', 'country': 'UK', 'founded_year': 1922, 'description': 'British luxury car manufacturer'},
            {'name': 'Land Rover', 'country': 'UK', 'founded_year': 1978, 'description': 'British SUV manufacturer'},
            {'name': 'Range Rover', 'country': 'UK', 'founded_year': 1970, 'description': 'Luxury SUV brand'},
            {'name': 'Bentley', 'country': 'UK', 'founded_year': 1919, 'description': 'British luxury car maker'},
            {'name': 'Rolls-Royce', 'country': 'UK', 'founded_year': 1904, 'description': 'Ultra-luxury automotive brand'},
            {'name': 'Ferrari', 'country': 'Italy', 'founded_year': 1939, 'description': 'Italian luxury sports car manufacturer'},
            {'name': 'Lamborghini', 'country': 'Italy', 'founded_year': 1963, 'description': 'Italian luxury sports car brand'},
            {'name': 'Maserati', 'country': 'Italy', 'founded_year': 1914, 'description': 'Italian luxury vehicle manufacturer'},
            {'name': 'Aston Martin', 'country': 'UK', 'founded_year': 1913, 'description': 'British luxury sports car manufacturer'},
            {'name': 'McLaren', 'country': 'UK', 'founded_year': 1963, 'description': 'British automotive manufacturer'},
            {'name': 'Bugatti', 'country': 'France', 'founded_year': 1909, 'description': 'French hypercar manufacturer'},
            {'name': 'Koenigsegg', 'country': 'Sweden', 'founded_year': 1994, 'description': 'Swedish hypercar manufacturer'},
            {'name': 'Genesis', 'country': 'South Korea', 'founded_year': 2015, 'description': 'Luxury vehicle division of Hyundai'},
            {'name': 'Acura', 'country': 'Japan', 'founded_year': 1986, 'description': 'Luxury vehicle division of Honda'},
            {'name': 'Infiniti', 'country': 'Japan', 'founded_year': 1989, 'description': 'Luxury vehicle division of Nissan'},
            {'name': 'Cadillac', 'country': 'USA', 'founded_year': 1902, 'description': 'American luxury vehicle marque'},
            {'name': 'Lincoln', 'country': 'USA', 'founded_year': 1917, 'description': 'American luxury vehicle brand'},
        ]
        
        makes = {}
        for make_data in makes_data:
            make, created = Make.objects.get_or_create(
                name=make_data['name'],
                defaults=make_data
            )
            makes[make.name] = make
            if created:
                self.stdout.write(f'✓ Created make: {make.name}')
        
        # Comprehensive sample cars data
        sample_cars = [
            # Mercedes-Benz
            {
                'make': makes['Mercedes-Benz'],
                'model': 'S-Class S580',
                'year': 2024,
                'price': 125000,
                'mileage': 500,
                'vin': 'W1K6G8DB3RA123456',
                'registration': 'CA-ABC123',
                'transmission': 'automatic',
                'fuel_type': 'hybrid',
                'body_style': 'sedan',
                'color': 'Obsidian Black',
                'engine_size': '4.0L V8',
                'horsepower': 496,
                'doors': 4,
                'seats': 5,
                'description': 'The pinnacle of luxury sedans with cutting-edge technology and supreme comfort.',
                'features': 'MBUX Hyperscreen, AIRMATIC suspension, Burmester 4D sound system, Night Vision, Energizing Comfort',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
                'image': 'media/cars/main/mercedes suv.web',
            },
            {
                'make': makes['Mercedes-Benz'],
                'model': 'GLE 450',
                'year': 2023,
                'price': 78900,
                'mileage': 8500,
                'vin': 'W1N8G4EB8PA234567',
                'registration': 'CA-DEF456',
                'transmission': 'automatic',
                'fuel_type': 'hybrid',
                'body_style': 'suv',
                'color': 'Polar White',
                'engine_size': '3.0L I6',
                'horsepower': 362,
                'doors': 4,
                'seats': 5,
                'description': 'Luxury midsize SUV with perfect balance of performance and comfort.',
                'features': 'Panoramic sunroof, Heated/Ventilated seats, Driver Assistance Package, Air suspension',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Mercedes-Benz'],
                'model': 'E-Class E350',
                'year': 2022,
                'price': 56900,
                'mileage': 18500,
                'vin': 'W1K3G5BB9NA345678',
                'registration': 'CA-GHI789',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Selenite Grey',
                'engine_size': '2.0L I4',
                'horsepower': 255,
                'doors': 4,
                'seats': 5,
                'description': 'Executive luxury sedan with refined performance and advanced technology.',
                'features': 'MBUX infotainment, LED headlights, Parking package, Ambient lighting',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': True,
            },
            {
                'make': makes['Mercedes-Benz'],
                'model': 'AMG GT 63 S',
                'year': 2024,
                'price': 185000,
                'mileage': 250,
                'vin': 'W1KEF5HB7RA456789',
                'registration': 'CA-JKL012',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Sun Yellow',
                'engine_size': '4.0L V8',
                'horsepower': 630,
                'doors': 2,
                'seats': 4,
                'description': 'High-performance coupe with racetrack capabilities and daily usability.',
                'features': 'AMG Performance exhaust, Carbon ceramic brakes, AMG Track Pace, Rear-wheel steering',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # BMW
            {
                'make': makes['BMW'],
                'model': 'M8 Competition',
                'year': 2024,
                'price': 152000,
                'mileage': 1200,
                'vin': 'WBS83CV05NCF56789',
                'registration': 'CA-MNO345',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Marina Bay Blue',
                'engine_size': '4.4L V8',
                'horsepower': 617,
                'doors': 2,
                'seats': 4,
                'description': 'The ultimate luxury sports coupe with uncompromising performance.',
                'features': 'M Sport exhaust, Carbon roof, Bowers & Wilkins audio, Laser headlights, M Carbon seats',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['BMW'],
                'model': 'X7 M60i',
                'year': 2023,
                'price': 112000,
                'mileage': 7500,
                'vin': '5UX83DP05P9X67890',
                'registration': 'CA-PQR678',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'suv',
                'color': 'Mineral White',
                'engine_size': '4.4L V8',
                'horsepower': 523,
                'doors': 4,
                'seats': 7,
                'description': 'Flagship luxury SUV with commanding presence and powerful performance.',
                'features': 'Executive package, Sky Lounge panoramic roof, Heated/Cooled cupholders, Glass controls',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['BMW'],
                'model': 'i7 xDrive60',
                'year': 2024,
                'price': 135000,
                'mileage': 800,
                'vin': 'WBA71EV020C78901',
                'registration': 'CA-STU901',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'sedan',
                'color': 'Black Sapphire',
                'engine_size': 'Dual Motor',
                'horsepower': 536,
                'doors': 4,
                'seats': 5,
                'description': 'All-electric luxury sedan with revolutionary technology and supreme comfort.',
                'features': 'Theatre Screen, Sky Lounge全景天窗, Bowers & Wilkins Diamond音响, Executive Lounge',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Tesla
            {
                'make': makes['Tesla'],
                'model': 'Model S Plaid',
                'year': 2024,
                'price': 135990,
                'mileage': 1500,
                'vin': '5YJSA1E5XMF123456',
                'registration': 'CA-VWX234',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'sedan',
                'color': 'Ultra Red',
                'engine_size': 'Tri-motor',
                'horsepower': 1020,
                'doors': 4,
                'seats': 5,
                'description': 'The quickest production car in the world with incredible technology.',
                'features': 'Plaid powertrain, Yoke steering, 17" infotainment, 390-mile range, 200 mph top speed',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Tesla'],
                'model': 'Model X Plaid',
                'year': 2023,
                'price': 119990,
                'mileage': 8500,
                'vin': '5YJXCAE26PF234567',
                'registration': 'CA-YZA567',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'suv',
                'color': 'Pearl White',
                'engine_size': 'Tri-motor',
                'horsepower': 1020,
                'doors': 4,
                'seats': 6,
                'description': 'All-electric SUV with falcon wing doors and incredible performance.',
                'features': 'Falcon Wing doors, 17" infotainment, 6-seat configuration, 348-mile range',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Porsche
            {
                'make': makes['Porsche'],
                'model': '911 Turbo S',
                'year': 2024,
                'price': 235000,
                'mileage': 800,
                'vin': 'WP0AB2A99PS123456',
                'registration': 'CA-BCD890',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Guards Red',
                'engine_size': '3.8L Flat-6',
                'horsepower': 640,
                'doors': 2,
                'seats': 4,
                'description': 'Iconic sports car with breathtaking performance and daily usability.',
                'features': 'Sport Chrono, Carbon ceramic brakes, Burmester音响, Front axle lift, Night Vision',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Porsche'],
                'model': 'Taycan Turbo S',
                'year': 2024,
                'price': 195000,
                'mileage': 1200,
                'vin': 'WP0ZZZY1ZLS234567',
                'registration': 'CA-EFG123',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'sedan',
                'color': 'Gentian Blue',
                'engine_size': 'Dual Motor',
                'horsepower': 750,
                'doors': 4,
                'seats': 4,
                'description': 'Electric sports sedan with Porsche performance and luxury.',
                'features': 'Performance Battery Plus, Porsche Torque Vectoring, Porsche Ceramic Composite Brakes',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Audi
            {
                'make': makes['Audi'],
                'model': 'RS e-tron GT',
                'year': 2024,
                'price': 145000,
                'mileage': 1500,
                'vin': 'WA1BVCFL8PD345678',
                'registration': 'CA-HIJ456',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'sedan',
                'color': 'Daytona Grey',
                'engine_size': 'Dual Motor',
                'horsepower': 590,
                'doors': 4,
                'seats': 4,
                'description': 'Electric grand tourer with stunning design and performance.',
                'features': 'Matrix LED headlights, Bang & Olufsen 3D音响, RS Sport package, Carbon package',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Lexus
            {
                'make': makes['Lexus'],
                'model': 'LC 500 Convertible',
                'year': 2023,
                'price': 112000,
                'mileage': 9500,
                'vin': 'JTHK2ABA3P5123456',
                'registration': 'CA-KLM789',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'convertible',
                'color': 'Infrared',
                'engine_size': '5.0L V8',
                'horsepower': 471,
                'doors': 2,
                'seats': 4,
                'description': 'Luxury convertible with naturally aspirated V8 and stunning design.',
                'features': 'Mark Levinson音响, 4-wheel steering, Active rear spoiler, Leather/Alcantara interior',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Range Rover
            {
                'make': makes['Range Rover'],
                'model': 'Autobiography',
                'year': 2024,
                'price': 185000,
                'mileage': 1200,
                'vin': 'SALWR2FV7PA234567',
                'registration': 'CA-NOP012',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'suv',
                'color': 'Carpathian Grey',
                'engine_size': '4.4L V8',
                'horsepower': 523,
                'doors': 4,
                'seats': 5,
                'description': 'The ultimate luxury SUV with unparalleled refinement and capability.',
                'features': 'Executive Class seating, Meridian音响, Terrain Response 2, Air suspension',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Ferrari
            {
                'make': makes['Ferrari'],
                'model': 'Roma',
                'year': 2024,
                'price': 245000,
                'mileage': 500,
                'vin': 'ZFF97VLA3R0256789',
                'registration': 'CA-QRS345',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Rosso Corsa',
                'engine_size': '3.9L V8',
                'horsepower': 612,
                'doors': 2,
                'seats': 2,
                'description': 'Front-engined GT with elegant design and thrilling performance.',
                'features': '8-speed DCT, Side Slip Control, Ferrari Dynamic Enhancer, Leather/Alcantara interior',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Lamborghini
            {
                'make': makes['Lamborghini'],
                'model': 'Huracán EVO',
                'year': 2023,
                'price': 285000,
                'mileage': 2500,
                'vin': 'ZHWUF8ZD5PLA78901',
                'registration': 'CA-TUV678',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Arancio Borealis',
                'engine_size': '5.2L V10',
                'horsepower': 631,
                'doors': 2,
                'seats': 2,
                'description': 'V10-powered supercar with razor-sharp handling and dramatic styling.',
                'features': 'Lamborghini Dinamica Veicolo Integrata, Carbon ceramic brakes, Forged wheels',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # Affordable Cars
            {
                'make': makes['BMW'],
                'model': '330i',
                'year': 2022,
                'price': 42900,
                'mileage': 22500,
                'vin': '3MW5R1J04N8B12345',
                'registration': 'CA-WXY901',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Alpine White',
                'engine_size': '2.0L I4',
                'horsepower': 255,
                'doors': 4,
                'seats': 5,
                'description': 'Sporty luxury sedan with excellent fuel economy and premium features.',
                'features': 'Premium package, Heated seats, Parking assistant, Live Cockpit Professional',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Audi'],
                'model': 'A4 Premium',
                'year': 2021,
                'price': 38900,
                'mileage': 28500,
                'vin': 'WAUANAF77MN012345',
                'registration': 'CA-ZAB234',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Monsoon Grey',
                'engine_size': '2.0L I4',
                'horsepower': 201,
                'doors': 4,
                'seats': 5,
                'description': 'Entry-level luxury sedan with Audi quality and technology.',
                'features': 'Virtual Cockpit, Apple CarPlay, LED headlights, Heated front seats',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Mercedes-Benz'],
                'model': 'C300',
                'year': 2020,
                'price': 36900,
                'mileage': 32500,
                'vin': '55SWF4EB7LU123456',
                'registration': 'CA-CDE567',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Iridium Silver',
                'engine_size': '2.0L I4',
                'horsepower': 255,
                'doors': 4,
                'seats': 5,
                'description': 'Compact luxury sedan with Mercedes-Benz prestige and comfort.',
                'features': 'MBUX infotainment, Panoramic roof, Memory package, Blind spot assist',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # More Luxury SUVs
            {
                'make': makes['Bentley'],
                'model': 'Bentayga V8',
                'year': 2023,
                'price': 195000,
                'mileage': 8500,
                'vin': 'SCBFR7ZA5LC012345',
                'registration': 'CA-FGH890',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'suv',
                'color': 'Mulliner Blue',
                'engine_size': '4.0L V8',
                'horsepower': 542,
                'doors': 4,
                'seats': 5,
                'description': 'Ultra-luxury SUV with handcrafted interior and powerful performance.',
                'features': 'Naim音响, Touring specification, Mood lighting, Rear seat entertainment',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Rolls-Royce'],
                'model': 'Cullinan',
                'year': 2024,
                'price': 385000,
                'mileage': 600,
                'vin': 'SCA681S58PUX12345',
                'registration': 'CA-IJK123',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'suv',
                'color': 'Magma Red',
                'engine_size': '6.75L V12',
                'horsepower': 563,
                'doors': 4,
                'seats': 4,
                'description': 'The Rolls-Royce of SUVs with ultimate luxury and presence.',
                'features': 'Starlight headliner, Bespoke audio, Champagne cooler, Lounge seats',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': True,
            },
            
            # Electric Vehicles
            {
                'make': makes['Porsche'],
                'model': 'Taycan 4S',
                'year': 2023,
                'price': 112000,
                'mileage': 12500,
                'vin': 'WP0ZZZY1ZLS345678',
                'registration': 'CA-LMN456',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'sedan',
                'color': 'Carrara White',
                'engine_size': 'Dual Motor',
                'horsepower': 522,
                'doors': 4,
                'seats': 4,
                'description': 'Electric sports sedan with Porsche DNA and daily usability.',
                'features': 'Performance Battery, Porsche Electric Sport Sound, Adaptive air suspension',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Audi'],
                'model': 'Q8 e-tron',
                'year': 2024,
                'price': 89000,
                'mileage': 3200,
                'vin': 'WA1B4AFY6R0123456',
                'registration': 'CA-OPQ789',
                'transmission': 'automatic',
                'fuel_type': 'electric',
                'body_style': 'suv',
                'color': 'Glacier White',
                'engine_size': 'Dual Motor',
                'horsepower': 402,
                'doors': 4,
                'seats': 5,
                'description': 'Electric luxury SUV with long range and premium features.',
                'features': 'Virtual mirrors, Bang & Olufsen音响, Head-up display, Air suspension',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # More Sports Cars
            {
                'make': makes['McLaren'],
                'model': '720S',
                'year': 2022,
                'price': 315000,
                'mileage': 3500,
                'vin': 'SBM12DEC5KW123456',
                'registration': 'CA-RST012',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Silica White',
                'engine_size': '4.0L V8',
                'horsepower': 710,
                'doors': 2,
                'seats': 2,
                'description': 'Super Series McLaren with dihedral doors and incredible performance.',
                'features': 'Carbon fiber monocoque, Proactive Chassis Control, Variable drift control',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Aston Martin'],
                'model': 'DB12',
                'year': 2024,
                'price': 245000,
                'mileage': 900,
                'vin': 'SCFRE3BD5PGL12345',
                'registration': 'CA-UVW345',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'coupe',
                'color': 'Xenon Grey',
                'engine_size': '4.0L V8',
                'horsepower': 671,
                'doors': 2,
                'seats': 2,
                'description': 'The worlds first Super Tourer with unprecedented performance and luxury.',
                'features': 'Bowers & Wilkins音响, 10.25" infotainment, Carbon ceramic brakes, Active exhaust',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
            
            # More Sedans
            {
                'make': makes['Genesis'],
                'model': 'G90',
                'year': 2024,
                'price': 89000,
                'mileage': 2800,
                'vin': 'KMHL34CA2RU012345',
                'registration': 'CA-XYZ678',
                'transmission': 'automatic',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Havana Red',
                'engine_size': '3.5L V6',
                'horsepower': 409,
                'doors': 4,
                'seats': 5,
                'description': 'Flagship luxury sedan with exceptional value and premium features.',
                'features': '3D仪表盘, 23-speaker Bang & Olufsen, Rear seat relaxation, Air suspension',
                'is_featured': False,
                'is_sold': False,
                'is_reserved': False,
            },
            {
                'make': makes['Cadillac'],
                'model': 'CT5-V Blackwing',
                'year': 2023,
                'price': 98500,
                'mileage': 6500,
                'vin': '1G6DP5ED5N0123456',
                'registration': 'CA-AAA901',
                'transmission': 'manual',
                'fuel_type': 'petrol',
                'body_style': 'sedan',
                'color': 'Rift Metallic',
                'engine_size': '6.2L V8',
                'horsepower': 668,
                'doors': 4,
                'seats': 5,
                'description': 'American performance sedan with manual transmission and supercharged V8.',
                'features': 'Magnetic Ride Control, Brembo brakes, Performance数据记录仪, Carbon fiber package',
                'is_featured': True,
                'is_sold': False,
                'is_reserved': False,
            },
        ]
        
        # Create cars
        created_count = 0
        for car_data in sample_cars:
            car, created = Car.objects.get_or_create(
                vin=car_data['vin'],
                defaults=car_data
            )
            if created:
                created_count += 1
                
                # Randomize created_at dates (for new arrivals filter)
                days_ago = random.randint(0, 90)
                car.created_at = date.today() - timedelta(days=days_ago)
                car.save()
        
        self.stdout.write(self.style.SUCCESS(f'✓ Created {created_count} cars'))
        
        # Create test users
        admin, created = User.objects.get_or_create(
            username='admin',
            defaults={
                'email': 'admin@luxurycars.com',
                'is_staff': True,
                'is_superuser': True
            }
        )
        if created:
            admin.set_password('admin123')
            admin.save()
            self.stdout.write('✓ Created admin user')
        
        user, created = User.objects.get_or_create(
            username='testuser',
            defaults={'email': 'user@luxurycars.com'}
        )
        if created:
            user.set_password('test123')
            user.save()
            self.stdout.write('✓ Created test user')
        
        self.stdout.write(self.style.SUCCESS('\n✅ Sample data creation complete!'))
        self.stdout.write('\n📊 Statistics:')
        self.stdout.write(f'  - Total makes: {Make.objects.count()}')
        self.stdout.write(f'  - Total cars: {Car.objects.count()}')
        self.stdout.write(f'  - Featured cars: {Car.objects.filter(is_featured=True).count()}')
        self.stdout.write(f'  - Available cars: {Car.objects.filter(is_sold=False).count()}')
        self.stdout.write(f'  - New arrivals (last 30 days): {Car.objects.filter(created_at__gte=date.today()-timedelta(days=30)).count()}')