# Generated by Django 6.0 on 2026-02-10 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='make/logo')),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.IntegerField(help_text='Mileage in Kilometers/Miles')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('registration', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi_Auto', 'Semi_Automatic')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plugin_hybrid', 'Plugin_Hybrid')], max_length=20)),
                ('body_style', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'Suv'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('truck', 'Truck')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('engine_size', models.CharField(help_text='e.g., 3.0L V6', max_length=50)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('doors', models.IntegerField(default=4)),
                ('seats', models.IntegerField(default=5)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='List features separated by commas')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(blank=True, upload_to='cars/main/')),
                ('image_1', models.ImageField(blank=True, upload_to='cars/gallery/')),
                ('image_2', models.ImageField(blank=True, upload_to='cars/gallery/')),
                ('image_3', models.ImageField(blank=True, upload_to='cars/gallery/')),
                ('image_4', models.ImageField(blank=True, upload_to='cars/gallery/')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_cars', to=settings.AUTH_USER_MODEL)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.make')),
            ],
            options={
                'ordering': ['-created_at', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='cars.car')),
            ],
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='cars_car_year_fc6735_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['mileage'], name='cars_car_mileage_f4d08e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='cars_car_make_id_c2711b_idx'),
        ),
    ]
